plugin.multiple.jar=plugins/generadorMultiple/target/generador-multiple-1.0-SNAPSHOT.jar
plugin.multiple.class=com.taller2.plugins.GeneradorPreguntasSeleccionMultiple
plugin.multiple.enabled=true
plugin.multimedia.jar=plugins/generadorMultimedia/target/generador-multimedia-1.0-SNAPSHOT.jar
plugin.multimedia.class=com.taller2.plugins.GeneradorPreguntaMultimedia
plugin.multimedia.enabled=true
plugin.excel.jar=plugins/importadorExcel/target/importador-excel-1.0-SNAPSHOT.jar
plugin.excel.class=com.taller2.plugins.ImportadorPreguntasExcel
plugin.excel.enabled=true
